-- Runs on every application startup (see spring.sql.init in application.yml), before
-- Hibernate's own ddl-auto:update schema check. Every statement here must stay idempotent
-- (safe to run against a database that already has the fix applied, and safe to run against
-- a brand new empty database) since there's no migration-version bookkeeping - this file is
-- the append-only history of one-off fixes Hibernate couldn't apply automatically on its own.
--
-- Statements are terminated with "//" (see spring.sql.init.separator), not ";" - Spring's
-- script splitter doesn't understand Postgres's $$ dollar-quoting and would otherwise cut a
-- DO $$ ... $$ block apart at the first ";" inside it.

-- Added when Edition gained a "type" column (FESTIVAL vs KNEIPENKONZERT): the old
-- uniqueness constraint on festival_year no longer applies once several Kneipenkonzerte can
-- share a year, and Hibernate can't add a NOT NULL column with no default to a table that
-- already has rows, so both steps have to happen here instead of via ddl-auto.
DO $$
DECLARE
    con_name text;
BEGIN
    IF to_regclass('editions') IS NULL THEN
        RETURN;
    END IF;

    SELECT conname INTO con_name
    FROM pg_constraint
    WHERE conrelid = 'editions'::regclass
      AND contype = 'u'
      AND conkey = (
          SELECT array_agg(attnum ORDER BY attnum)
          FROM pg_attribute
          WHERE attrelid = 'editions'::regclass AND attname = 'festival_year'
      );
    IF con_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE editions DROP CONSTRAINT %I', con_name);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'editions' AND column_name = 'type'
    ) THEN
        ALTER TABLE editions ADD COLUMN type varchar(255) NOT NULL DEFAULT 'FESTIVAL';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'editions_type_check') THEN
        ALTER TABLE editions ADD CONSTRAINT editions_type_check CHECK (type IN ('FESTIVAL', 'KNEIPENKONZERT'));
    END IF;
END $$//

-- Added when the venue became a central, reusable Location entity: editions now
-- reference one via location_id instead of storing locationName/locationStreet/
-- locationZipCity inline, and headlinerName/headlinerDateLabel are computed from
-- the location + dates instead of stored (see Location.java, Edition.java). This
-- creates the locations table itself (normally Hibernate's job) because it needs
-- to write to it before Hibernate gets a chance to create it.
DO $$
BEGIN
    IF to_regclass('editions') IS NULL THEN
        RETURN;
    END IF;

    IF to_regclass('locations') IS NULL THEN
        CREATE TABLE locations (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name varchar(255) NOT NULL,
            street varchar(255),
            zip_city varchar(255)
        );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'editions' AND column_name = 'location_id'
    ) THEN
        ALTER TABLE editions ADD COLUMN location_id bigint REFERENCES locations(id);
    END IF;

    -- One-time backfill: for every edition that still has inline location text but
    -- no location_id yet, reuse a matching Location or create one, then link it.
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'editions' AND column_name = 'location_name'
    ) THEN
        INSERT INTO locations (name, street, zip_city)
        SELECT DISTINCT e.location_name, e.location_street, e.location_zip_city
        FROM editions e
        WHERE e.location_id IS NULL
          AND e.location_name IS NOT NULL
          AND NOT EXISTS (
              SELECT 1 FROM locations l
              WHERE l.name = e.location_name
                AND l.street IS NOT DISTINCT FROM e.location_street
                AND l.zip_city IS NOT DISTINCT FROM e.location_zip_city
          );

        UPDATE editions e
        SET location_id = l.id
        FROM locations l
        WHERE e.location_id IS NULL
          AND e.location_name IS NOT NULL
          AND l.name = e.location_name
          AND l.street IS NOT DISTINCT FROM e.location_street
          AND l.zip_city IS NOT DISTINCT FROM e.location_zip_city;

        ALTER TABLE editions DROP COLUMN location_name;
        ALTER TABLE editions DROP COLUMN location_street;
        ALTER TABLE editions DROP COLUMN location_zip_city;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'editions' AND column_name = 'headliner_name'
    ) THEN
        ALTER TABLE editions DROP COLUMN headliner_name;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'editions' AND column_name = 'headliner_date_label'
    ) THEN
        ALTER TABLE editions DROP COLUMN headliner_date_label;
    END IF;
END $$//

-- Added when "Textfarbe" was dropped from the color scheme: it always matched
-- "Akzentfarbe" in practice, so the Farbkonzept form now only asks for
-- Primär-/Sekundär-/Akzentfarbe, and text color is just the accent color
-- wherever it's used (see fragments/head.html).
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'editions' AND column_name = 'color_text'
    ) THEN
        ALTER TABLE editions DROP COLUMN color_text;
    END IF;
END $$//

-- Added when "Anzeige-Label (Hero)" was dropped for Kneipenkonzerte (the year isn't
-- relevant there): clears it for any that already have one, so the label box under
-- the title stops showing without needing every one to be re-saved through the form.
DO $$
BEGIN
    IF to_regclass('editions') IS NULL THEN
        RETURN;
    END IF;

    UPDATE editions SET display_label = '' WHERE type = 'KNEIPENKONZERT' AND display_label <> '';
END $$//
